# Generated by Django 3.1 on 2020-09-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlog',
            name='book',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
