# Generated by Django 3.1 on 2020-09-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientManager', '0002_backlog_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlog',
            name='value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
